export const POSTING_HASHTAG = "POSTING_HASHTAG";
export const FETCHING_DATA = "FETCHING_DATA";
export const FAILED_FETCHING_DATA = "FAILED_FETCHING_DATA";
export const FAILED_POSTING_HASHTAG = "FAILED_POSTING_HASHTAG";
export const ADD_TWEETS = "ADD_TWEETS";
export const ADD_API_RESPONSE = "ADD_API_RESPONSE";
export const FAILED_POSTING = "FAILED_POSTING";
